import { defineSupervisorIpcHandlers, type SupervisorIpcHandlerMap } from "@/shared/ipc";
import type { SupervisorRuntime } from "./runtime";

export function createSupervisorIpcHandlers(runtime: SupervisorRuntime): SupervisorIpcHandlerMap {
  return defineSupervisorIpcHandlers({
    listWslDistros: () => runtime.listWslDistros(),
    getAgentStatuses: (payload) => runtime.getAgentStatuses(payload),
    getThreadSnapshots: () => runtime.getThreadSnapshots(),
    startThread: (payload) => runtime.startThread(payload),
    sendThreadInput: (payload) => runtime.sendThreadInput(payload),
    writeTerminal: (payload) => runtime.writeTerminal(payload),
    resizeTerminal: (payload) => runtime.resizeTerminal(payload),
    resolveThreadServerRequest: (payload) => runtime.resolveThreadServerRequest(payload),
    closeThread: (payload) => runtime.closeThread(payload),
    startShell: (payload) => runtime.startShell(payload),
    extractContext: (payload) => runtime.extractContext(payload),
    cancelExtractContext: ({ threadId }) => runtime.cancelExtractContext(threadId),
    readTerminalScrollback: ({ threadId }) => runtime.readTerminalScrollback(threadId),
    getGitStatus: (payload) => runtime.getGitStatus(payload),
    getGitDiff: (payload) => runtime.getGitDiff(payload),
    getGitDiffBatch: (payload) => runtime.getGitDiffBatch(payload),
    getGitFileContent: (payload) => runtime.getGitFileContent(payload),
    gitStage: (payload) => runtime.gitStage(payload),
    gitUnstage: (payload) => runtime.gitUnstage(payload),
    gitRevert: (payload) => runtime.gitRevert(payload),
    gitStageAll: (payload) => runtime.gitStageAll(payload),
    gitUnstageAll: (payload) => runtime.gitUnstageAll(payload),
    gitRevertAll: (payload) => runtime.gitRevertAll(payload),
    gitCommit: (payload) => runtime.gitCommit(payload),
    generateCommitMessage: (payload) => runtime.generateCommitMessage(payload),
    generateTitle: (payload) => runtime.generateTitle(payload),
    generatePrSummary: (payload) => runtime.generatePrSummary(payload),
    gitListBranches: (payload) => runtime.gitListBranches(payload),
    gitFetch: (payload) => runtime.gitFetch(payload),
    gitListWorktrees: (payload) => runtime.gitListWorktrees(payload),
    gitAddWorktree: (payload) => runtime.gitAddWorktree(payload),
    gitRemoveWorktree: (payload) => runtime.gitRemoveWorktree(payload),
    gitPruneWorktrees: (payload) => runtime.gitPruneWorktrees(payload),
    gitDeleteBranch: (payload) => runtime.gitDeleteBranch(payload),
    gitSwitchBranch: (payload) => runtime.gitSwitchBranch(payload),
    gitPull: (payload) => runtime.gitPull(payload),
    gitPush: (payload) => runtime.gitPush(payload),
    gitSync: (payload) => runtime.gitSync(payload),
    gitGetWorktreeSourceBranch: (payload) => runtime.gitGetWorktreeSourceBranch(payload),
    gitMergeToSource: (payload) => runtime.gitMergeToSource(payload),
    gitPullFromSource: (payload) => runtime.gitPullFromSource(payload),
    gitAbortMerge: (payload) => runtime.gitAbortMerge(payload),
    gitRunMergetool: (payload) => runtime.gitRunMergetool(payload),
    gitFinishMerge: (payload) => runtime.gitFinishMerge(payload),
    gitWatchProject: (payload) => runtime.gitWatchProject(payload),
    gitWatchWorktrees: (payload) => runtime.gitWatchWorktrees(payload),
    gitUnwatchProject: (payload) => runtime.gitUnwatchProject(payload),
    searchProjectFiles: (payload) => runtime.searchProjectFiles(payload),
    listProjectTree: (payload) => runtime.listProjectTree(payload),
    searchProjectTree: (payload) => runtime.searchProjectTree(payload),
    readProjectFile: (payload) => runtime.readProjectFile(payload),
    writeProjectFile: (payload) => runtime.writeProjectFile(payload),
    createProjectEntry: (payload) => runtime.createProjectEntry(payload),
    renameProjectEntry: (payload) => runtime.renameProjectEntry(payload),
    moveProjectEntry: (payload) => runtime.moveProjectEntry(payload),
    deleteProjectEntry: (payload) => runtime.deleteProjectEntry(payload),
    detectSetupScript: (payload) => runtime.detectSetupScript(payload),
    ghCheckAvailable: (payload) => runtime.ghCheckAvailable(payload),
    ghCreatePr: (payload) => runtime.ghCreatePr(payload),
    ghGetPrForBranch: (payload) => runtime.ghGetPrForBranch(payload),
    ghMergePr: (payload) => runtime.ghMergePr(payload),
    ghClosePr: (payload) => runtime.ghClosePr(payload),
    ghReopenPr: (payload) => runtime.ghReopenPr(payload),
    ghMarkPrReady: (payload) => runtime.ghMarkPrReady(payload),
    ghGetPrChecks: (payload) => runtime.ghGetPrChecks(payload),
    lspStart: (payload) => runtime.lspStart(payload),
    lspStop: (payload) => runtime.lspStop(payload),
    lspSendMessage: async (payload) => {
      await runtime.lspSendMessage(payload);
    },
  });
}
